controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    four_wheel_steering_controller:
      type: four_wheel_steering_controller/FourWheelSteeringController

forward_position_controller:
  ros__parameters:
    joints:
      - fl_steering_wheel
      - fr_steering_wheel
      - rl_steering_wheel
      - rr_steering_wheel
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

forward_velocity_controller:
  ros__parameters:
    joints:
      - fl_wheel
      - fr_wheel
      - rl_wheel
      - rr_wheel
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

four_wheel_steering_controller:
  ros__parameters:
    front_left_wheel: fl_wheel
    front_right_wheel: fr_wheel
    rear_left_wheel: rl_wheel
    rear_right_wheel: rr_wheel
    front_left_steering: fl_steering_wheel
    front_right_steering: fr_steering_wheel
    rear_left_steering: rl_steering_wheel
    rear_right_steering: rr_steering_wheel
    chassis_type: flrr # all-四舵轮(全), flrr-四舵轮(前左fl,后右rr), frrl-四舵轮(前右fr,后左rl)

    track: 0.394
    wheel_radius: 0.1
    wheel_base: 0.364
    wheel_steering_y_offset: 0.05

    # track: 0.423065
    # wheel_radius: 0.1
    # wheel_base: 0.490102
    # wheel_steering_y_offset: 0.0316228

    # track: 0.423065
    # wheel_radius: 0.1
    # wheel_base: 0.364
    # wheel_steering_y_offset: 0.0316228

    publish_rate: 50.0
    open_loop: false
    enable_odom_tf: true
    cmd_vel_timeout: 1.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    wait_for_angle: true
    min_steering_diff: 0.02
    stop_no_adjust_steering: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.667  # m/s
        min_velocity           : -1.667 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 3.14  # rad/s
        min_velocity           : -3.14
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0