# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_right_position_controller:
      type: forward_command_controller/ForwardCommandController

    arm_left_position_controller:
      type: forward_command_controller/ForwardCommandController

    four_wheel_steering_controller:
      type: four_wheel_steering_controller/FourWheelSteeringController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    # arm_right_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    # arm_left_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    # gripper_left_controller:
    #   type: position_controllers/GripperActionController

    # gripper_right_controller:
    #   type: position_controllers/GripperActionController

    gripper_left_controller:
      type: forward_command_controller/ForwardCommandController

    gripper_right_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_right_position_controller:
  ros__parameters:
    joints:
      - arm_right_joint1
      - arm_right_joint2
      - arm_right_joint3
      - arm_right_joint4
      - arm_right_joint5
      - arm_right_joint6
      - arm_right_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

arm_left_position_controller:
  ros__parameters:
    joints:
      - arm_left_joint1
      - arm_left_joint2
      - arm_left_joint3
      - arm_left_joint4
      - arm_left_joint5
      - arm_left_joint6
      - arm_left_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

four_wheel_steering_controller:
  ros__parameters:
    front_left_wheel: fl_wheel
    front_right_wheel: fr_wheel
    rear_left_wheel: rl_wheel
    rear_right_wheel: rr_wheel
    front_left_steering: fl_steering_wheel
    front_right_steering: fr_steering_wheel
    rear_left_steering: rl_steering_wheel
    rear_right_steering: rr_steering_wheel
    chassis_type: flrr # all-四舵轮(全), flrr-四舵轮(前左fl,后右rr), frrl-四舵轮(前右fr,后左rl)

    track: 0.394
    wheel_radius: 0.1
    wheel_base: 0.364
    wheel_steering_y_offset: 0.05

    # track: 0.423065
    # wheel_radius: 0.1
    # wheel_base: 0.490102
    # wheel_steering_y_offset: 0.0316228

    publish_rate: 50.0
    open_loop: true
    enable_odom_tf: false
    cmd_vel_timeout: 1.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    wait_for_angle: false
    # wait_for_angle: true
    min_steering_diff: 0.15
    stop_no_adjust_steering: false

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.667  # m/s
        min_velocity           : -1.667 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 3.14  # rad/s
        min_velocity           : -3.14
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0

forward_position_controller:
  ros__parameters:
    joints:
      - fl_steering_wheel
      - fr_steering_wheel
      - rl_steering_wheel
      - rr_steering_wheel
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

forward_velocity_controller:
  ros__parameters:
    joints:
      - fl_wheel
      - fr_wheel
      - rl_wheel
      - rr_wheel
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      
# arm_right_trajectory_controller:
#   ros__parameters:
#     joints:
#       - arm_right_shoulder_pitch_joint
#       - arm_right_shoulder_roll_joint
#       - arm_right_shoulder_yaw_joint
#       - arm_right_elbow_pitch_joint
#       - arm_right_elbow_roll_joint
#       - arm_right_wrist_pitch_joint
#       - arm_right_wrist_yaw_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

# arm_left_trajectory_controller:
#   ros__parameters:
#     joints:
#       - arm_left_shoulder_pitch_joint
#       - arm_left_shoulder_roll_joint
#       - arm_left_shoulder_yaw_joint
#       - arm_left_elbow_pitch_joint
#       - arm_left_elbow_roll_joint
#       - arm_left_wrist_pitch_joint
#       - arm_left_wrist_yaw_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

# 夹爪控制器
gripper_left_controller:
  ros__parameters:
    joints: 
      - gripper_left_joint
      - gripper_left_joint_mimic
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    # default: true
    # joint: gripper_left_joint
    # use_effort_interface: true
    # use_speed_interface: true

    # action_monitor_rate: 20.0
    # allow_stalling: false
    # goal_tolerance: 0.01
    # joint: gripper_left_joint
    # max_effort: 10.0
    # stall_timeout: 1.0
    # stall_velocity_threshold: 0.001
    # command_interface_name: position
    # command_topic: /gripper_left_controller/command

gripper_right_controller:
  ros__parameters:
    joints: 
      - gripper_right_joint
      - gripper_right_joint_mimic
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    # default: true
    # joint: gripper_right_joint
    # use_effort_interface: true
    # use_speed_interface: true

    # action_monitor_rate: 20.0
    # allow_stalling: false
    # goal_tolerance: 0.01
    # joint: gripper_right_joint
    # max_effort: 10.0
    # stall_timeout: 1.0
    # stall_velocity_threshold: 0.001
    # # command_interface_name: position
    # # command_topic: /gripper_right_controller/command