# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    # arm_right_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    # arm_left_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    four_wheel_steering_controller:
      type: four_wheel_steering_controller/FourWheelSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_right_trajectory_controller:
  ros__parameters:
    joints:
      - arm_right_shoulder_pitch_joint
      - arm_right_shoulder_roll_joint
      - arm_right_shoulder_yaw_joint
      - arm_right_elbow_pitch_joint
      - arm_right_elbow_roll_joint
      - arm_right_wrist_pitch_joint
      - arm_right_wrist_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

arm_left_trajectory_controller:
  ros__parameters:
    joints:
      - arm_left_shoulder_pitch_joint
      - arm_left_shoulder_roll_joint
      - arm_left_shoulder_yaw_joint
      - arm_left_elbow_pitch_joint
      - arm_left_elbow_roll_joint
      - arm_left_wrist_pitch_joint
      - arm_left_wrist_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

four_wheel_steering_controller:
  ros__parameters:
    front_left_wheel: front_left_wheel_wheel_joint
    front_right_wheel: front_right_wheel_wheel_joint
    rear_left_wheel: rear_left_wheel_wheel_joint
    rear_right_wheel: rear_right_wheel_wheel_joint
    front_left_steering: front_left_wheel_steering_joint
    front_right_steering: front_right_wheel_steering_joint
    rear_left_steering: rear_left_wheel_steering_joint
    rear_right_steering: rear_right_wheel_steering_joint
    chassis_type: flrr # all-四舵轮(全), flrr-四舵轮(前左fl,后右rr), frrl-四舵轮(前右fr,后左rl)

    track: 0.394
    wheel_radius: 0.1
    wheel_base: 0.364
    wheel_steering_y_offset: 0.05

    publish_rate: 50.0
    open_loop: false
    enable_odom_tf: true
    cmd_vel_timeout: 1.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    wait_for_angle: true
    min_steering_diff: 0.02
    stop_no_adjust_steering: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.667  # m/s
        min_velocity           : -1.667 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 3.14  # rad/s
        min_velocity           : -3.14
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0